name: fitsync
description: "A new health app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Correct SDK range for Flutter 3.x compatibility

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  http: ^0.13.0  # Ensure this is included for the API calls
  image_picker: ^0.8.7+4 # Use the latest version available
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.8
  video_player: ^2.9.1
  cached_network_image: ^3.3.1
  velocity_x: ^4.2.1
  jwt_decoder: ^2.0.1
  flutter_slidable: ^3.1.1
  webview_flutter: ^4.0.0 # Use the latest version available
  syncfusion_flutter_charts: ^27.1.48
  file_picker: ^8.1.2
  fl_chart: ^0.66.0
  mime: ^1.0.5
  http_parser: ^4.0.2
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  image_path: assets/images/logo.png
  min_sdk_android: 21 # android min sdk min:16, default 21s

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/homepage_bg.jpg


